name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to release (e.g. v0.1.0)"
        required: true

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          ref: refs/tags/${{ github.event.inputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-linux:
    needs: create-release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            build-tool: cargo
          - target: armv7-unknown-linux-gnueabihf
            build-tool: cross
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/setup-cross-toolchain-action@v1
        if: ${{ matrix.build-tool == 'cross' }}
        with:
          target: ${{ matrix.target }}
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: musrv
          target: ${{ matrix.target }}
          build-tool: ${{ matrix.build-tool }}
          ref: refs/tags/${{ github.event.inputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-macos:
    needs: create-release
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: musrv
          target: ${{ matrix.target }}
          ref: refs/tags/${{ github.event.inputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
