name: Release

on:
  push:
    tags: [ 'v*.*.*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-binaries:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: swatinem/rust-cache@v2

      - name: Build and upload binaries
        uses: taiki-e/upload-rust-binary@v1
        with:
          bin: musrv
          targets: |
            x86_64-unknown-linux-gnu
            aarch64-unknown-linux-gnu
            armv7-unknown-linux-gnueabihf
            x86_64-apple-darwin
            aarch64-apple-darwin
            x86_64-pc-windows-msvc
          use-cross: true
